name: Crowdin


on:
  push:
    branches: ["main"]
  workflow_dispatch:


jobs:
  synchronize-with-crowdin:

    runs-on: ubuntu-24.04

    steps:
      # https://github.com/actions/checkout
      - name: Checkout Git repository
        uses: actions/checkout@v5.0.0

      # https://github.com/crowdin/github-action
      - name: Crowdin action
        uses: crowdin/github-action@v2.10.0
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          download_sources: true
          create_pull_request: true
          pull_request_base_branch_name: 'main'
          localization_branch_name: 'l10n_main'
          commit_message: '[ci-skip] Commit new translations'
          pull_request_assignees: 'datatags'
          pull_request_title: 'New translations'
          pull_request_body: 'New translations are available via [Crowdin](https://crowdin.com/project/ultracosmetics)!'
        env:
          # A classic GitHub Personal Access Token with the 'repo' scope selected (the user should have write access to the repository).
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          # A numeric ID, found at https://crowdin.com/project/<projectName>/tools/api
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          # Visit https://crowdin.com/settings#api-key to create this token
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
